services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: supportly-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - supportly-sql-data:/var/opt/mssql

volumes:
  supportly-sql-data: